# Generated by Django 6.1 on 2026-08-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('regular', 'Regular'), ('hero', 'Hero'), ('thumbnail', 'Thumbnail'), ('logo', 'Logo')], max_length=20)),
                ('image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('original_format', models.CharField(max_length=10)),
                ('optimized_format', models.CharField(max_length=10)),
                ('original_size', models.PositiveIntegerField(help_text='bytes')),
                ('optimized_size', models.PositiveIntegerField(help_text='bytes')),
                ('target_size', models.PositiveIntegerField(help_text='bytes')),
                ('original_width', models.PositiveIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveIntegerField(blank=True, null=True)),
                ('optimized_width', models.PositiveIntegerField(blank=True, null=True)),
                ('optimized_height', models.PositiveIntegerField(blank=True, null=True)),
                ('method', models.CharField(choices=[('lossless', 'Lossless'), ('near_lossless', 'Near Lossless'), ('lossy', 'Lossy'), ('lossy_resized', 'Lossy + Resized'), ('forced_fit', 'Forced Fit'), ('skipped', 'Skipped (GIF/SVG/animated)'), ('not_needed', 'Already Under Target')], max_length=20)),
                ('quality', models.PositiveIntegerField(blank=True, null=True)),
                ('near_lossless_level', models.PositiveIntegerField(blank=True, null=True)),
                ('scale', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
