# Generated by Django 6.1 on 2026-08-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('desktop', 'Desktop')], max_length=10)),
                ('image', models.FileField(upload_to='uploads/variants/%Y/%m/%d/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('format', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='images.imageupload')),
            ],
            options={
                'ordering': ['width'],
                'constraints': [models.UniqueConstraint(fields=('image_upload', 'variant_type'), name='unique_image_upload_variant_type')],
            },
        ),
    ]
